// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


function isLeapYear(year) {
  var match = year % 4;
  if (match !== 0) {
    return false;
  } else {
    var match$1 = year % 100;
    var match$2 = year % 400;
    if (match$1 !== 0) {
      return true;
    } else {
      return match$2 === 0;
    }
  }
}

exports.isLeapYear = isLeapYear;
/* No side effect */
